import { useEffect, useRef, useState } from "react";
import { Link } from "@tanstack/react-router";
import { ArrowRight, ArrowUpRight, Bot, Download, Send, Sparkles } from "lucide-react";

type Msg = { role: "user" | "assistant"; content: string };

export type Proposal = {
  summary: string;
  recommendation: string;
  timeline: string;
  budgetMin: number;
  budgetMax: number;
  stack: string[];
  milestones?: string[];
};

const GREETING: Msg = {
  role: "assistant",
  content:
    "Hi — I'm Synvora's AI project consultant. In a minute or two I'll sketch a tailored proposal for you. To start: what would you like to build?",
};

export default function ConsultantChat() {
  const [messages, setMessages] = useState<Msg[]>([GREETING]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [proposal, setProposal] = useState<Proposal | null>(null);
  const scrollRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLTextAreaElement>(null);

  useEffect(() => {
    scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: "smooth" });
  }, [messages, loading]);

  const hasInteracted = useRef(false);
  useEffect(() => {
    if (!loading && hasInteracted.current) inputRef.current?.focus();
  }, [loading, proposal]);

  async function send() {
    const text = input.trim();
    if (!text || loading || proposal) return;
    hasInteracted.current = true;
    setError(null);
    const next = [...messages, { role: "user" as const, content: text }];
    setMessages(next);
    setInput("");
    setLoading(true);
    try {
      const res = await fetch("/api/consultant", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ messages: next }),
      });
      if (!res.ok) {
        const msg =
          res.status === 429
            ? "Rate limit reached — please wait a moment and try again."
            : res.status === 402
              ? "AI credits exhausted. Please contact us directly."
              : "Something went wrong. Please try again.";
        throw new Error(msg);
      }
      const data = (await res.json()) as { content: string; proposal: Proposal | null };
      if (data.content) {
        setMessages((m) => [...m, { role: "assistant", content: data.content }]);
      }
      if (data.proposal) setProposal(data.proposal);
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : "Something went wrong.");
    } finally {
      setLoading(false);
    }
  }

  function onKey(e: React.KeyboardEvent<HTMLTextAreaElement>) {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      send();
    }
  }

  function downloadProposal() {
    if (!proposal) return;
    const fmt = (n: number) => "€" + n.toLocaleString("en-US");
    const lines = [
      "SYNVORA — PROJECT PROPOSAL",
      "===========================",
      "",
      "PROJECT SUMMARY",
      proposal.summary,
      "",
      "RECOMMENDED SOLUTION",
      proposal.recommendation,
      "",
      `ESTIMATED TIMELINE: ${proposal.timeline}`,
      `ESTIMATED BUDGET: ${fmt(proposal.budgetMin)} – ${fmt(proposal.budgetMax)}`,
      "",
      "RECOMMENDED TECHNOLOGY STACK",
      proposal.stack.map((s) => "  • " + s).join("\n"),
      ...(proposal.milestones?.length
        ? ["", "KEY MILESTONES", proposal.milestones.map((m) => "  • " + m).join("\n")]
        : []),
      "",
      "Generated by Synvora AI Consultant",
    ];
    const blob = new Blob([lines.join("\n")], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "synvora-proposal.txt";
    a.click();
    URL.revokeObjectURL(url);
  }

  function reset() {
    setMessages([GREETING]);
    setProposal(null);
    setError(null);
    setInput("");
  }

  const fmtBudget = (n: number) => "€" + n.toLocaleString("en-US");

  return (
    <div className="relative overflow-hidden rounded-[28px] hairline-strong bg-[var(--surface)] p-6 sm:p-8">
      <div
        aria-hidden
        className="pointer-events-none absolute inset-0"
        style={{
          background:
            "radial-gradient(ellipse 60% 100% at 50% 0%, oklch(0.72 0.22 250 / 0.14), transparent 70%)",
        }}
      />

      {/* Header */}
      <div className="relative mb-6 flex items-center justify-between gap-4">
        <div className="flex min-w-0 items-center gap-3">
          <span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl hairline bg-[var(--surface-elevated)] text-[var(--electric)] shadow-[0_0_20px_-6px_var(--electric)]">
            <Bot className="h-4 w-4" strokeWidth={1.5} />
          </span>
          <div className="min-w-0">
            <p className="text-[10.5px] uppercase tracking-[0.22em] text-muted-foreground">Synvora Consultant</p>
            <p className="truncate font-display text-[15px] tracking-[-0.015em] text-foreground">
              {proposal ? "Proposal ready" : loading ? "Thinking…" : "Online — ready to help"}
            </p>
          </div>
        </div>
        <span className="flex items-center gap-1.5 rounded-full hairline bg-white/[0.02] px-2.5 py-1 text-[10.5px] text-foreground/70">
          <span className={`h-1.5 w-1.5 rounded-full ${loading ? "bg-yellow-400 animate-pulse" : "bg-[var(--electric)] shadow-[0_0_8px_var(--electric)]"}`} />
          {loading ? "AI typing" : "AI"}
        </span>
      </div>

      {!proposal ? (
        <>
          {/* Chat transcript */}
          <div
            ref={scrollRef}
            className="relative h-[420px] overflow-y-auto rounded-2xl hairline bg-black/30 p-5 sm:h-[460px]"
          >
            <div className="flex flex-col gap-4">
              {messages.map((m, i) => (
                <div key={i} className={`flex ${m.role === "user" ? "justify-end" : "justify-start"} animate-fade-in`}>
                  <div
                    className={`max-w-[85%] rounded-2xl px-4 py-3 text-[14px] leading-relaxed ${
                      m.role === "user"
                        ? "bg-white text-black shadow-[0_10px_30px_-15px_oklch(0.72_0.22_250/0.6)]"
                        : "hairline bg-white/[0.03] text-foreground/90"
                    }`}
                  >
                    {m.content}
                  </div>
                </div>
              ))}
              {loading && (
                <div className="flex justify-start">
                  <div className="hairline flex items-center gap-1.5 rounded-2xl bg-white/[0.03] px-4 py-3">
                    <span className="h-1.5 w-1.5 animate-bounce rounded-full bg-foreground/60" style={{ animationDelay: "0ms" }} />
                    <span className="h-1.5 w-1.5 animate-bounce rounded-full bg-foreground/60" style={{ animationDelay: "150ms" }} />
                    <span className="h-1.5 w-1.5 animate-bounce rounded-full bg-foreground/60" style={{ animationDelay: "300ms" }} />
                  </div>
                </div>
              )}
              {error && (
                <div className="rounded-xl border border-red-400/30 bg-red-500/10 px-4 py-3 text-[13px] text-red-200">
                  {error}
                </div>
              )}
            </div>
          </div>

          {/* Composer */}
          <div className="relative mt-4 flex items-end gap-2 rounded-2xl hairline bg-black/40 p-2">
            <textarea
              ref={inputRef}
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={onKey}
              rows={1}
              maxLength={1000}
              placeholder="Type your answer…"
              disabled={loading}
              className="max-h-40 min-h-[44px] w-full resize-none bg-transparent px-3 py-2.5 text-[14px] text-foreground placeholder:text-foreground/30 outline-none"
            />
            <button
              type="button"
              onClick={send}
              disabled={loading || !input.trim()}
              className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-white text-black transition-all duration-300 hover:shadow-[0_0_24px_-4px_oklch(0.72_0.22_250/0.9)] disabled:opacity-40 disabled:pointer-events-none"
              aria-label="Send"
            >
              <Send className="h-4 w-4" strokeWidth={2} />
            </button>
          </div>
          <p className="relative mt-3 text-[11px] text-muted-foreground">
            Synvora AI · your answers stay on this page until you request a proposal.
          </p>
        </>
      ) : (
        <div className="relative animate-fade-in">
          {/* Proposal Card */}
          <div className="rounded-2xl hairline-strong bg-black/40 p-6 sm:p-8">
            <div className="flex items-center gap-2">
              <Sparkles className="h-4 w-4 text-[var(--electric)]" />
              <p className="text-[10.5px] uppercase tracking-[0.22em] text-muted-foreground">Tailored proposal</p>
            </div>

            <h3 className="mt-4 font-display text-[24px] leading-tight tracking-[-0.025em] text-gradient sm:text-[28px]">
              Your Synvora project proposal
            </h3>

            <div className="mt-6 grid gap-6">
              <ProposalBlock label="Project Summary">{proposal.summary}</ProposalBlock>
              <ProposalBlock label="Recommended Solution">{proposal.recommendation}</ProposalBlock>

              <div className="grid gap-4 sm:grid-cols-2">
                <div className="rounded-xl hairline bg-white/[0.02] p-5">
                  <p className="text-[10.5px] uppercase tracking-[0.22em] text-muted-foreground">Estimated Timeline</p>
                  <p className="text-electric-gradient mt-2 font-display text-[26px] leading-none tracking-[-0.03em]">
                    {proposal.timeline}
                  </p>
                </div>
                <div className="rounded-xl hairline bg-white/[0.02] p-5">
                  <p className="text-[10.5px] uppercase tracking-[0.22em] text-muted-foreground">Estimated Budget</p>
                  <p className="text-electric-gradient mt-2 font-display text-[26px] leading-none tracking-[-0.03em]">
                    {fmtBudget(proposal.budgetMin)} – {fmtBudget(proposal.budgetMax)}
                  </p>
                </div>
              </div>

              <p className="text-[12px] leading-relaxed text-muted-foreground">
                AI-assisted delivery allows Synvora to reduce production time compared with traditional development. Final delivery time depends on project complexity, integrations, content readiness and approval speed.
              </p>

              <div>
                <p className="text-[10.5px] uppercase tracking-[0.22em] text-muted-foreground">Recommended Tech Stack</p>
                <div className="mt-3 flex flex-wrap gap-2">
                  {proposal.stack.map((s) => (
                    <span
                      key={s}
                      className="rounded-full hairline bg-white/[0.03] px-3 py-1.5 text-[12.5px] text-foreground/85"
                    >
                      {s}
                    </span>
                  ))}
                </div>
              </div>

              {proposal.milestones && proposal.milestones.length > 0 && (
                <div>
                  <p className="text-[10.5px] uppercase tracking-[0.22em] text-muted-foreground">Key Milestones</p>
                  <ol className="mt-3 space-y-2">
                    {proposal.milestones.map((m, i) => (
                      <li key={m} className="flex items-start gap-3 text-[13.5px] text-foreground/85">
                        <span className="mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-full hairline bg-white/[0.03] text-[10.5px] text-foreground/70">
                          {i + 1}
                        </span>
                        {m}
                      </li>
                    ))}
                  </ol>
                </div>
              )}
            </div>
          </div>

          <div className="mt-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
            <button
              type="button"
              onClick={reset}
              className="text-[13px] text-muted-foreground underline-offset-4 hover:text-foreground hover:underline"
            >
              Start over
            </button>
            <div className="flex flex-col gap-3 sm:flex-row">
              <button type="button" onClick={downloadProposal} className="btn-ghost group">
                Download Proposal
                <Download className="h-4 w-4 transition-transform duration-500 group-hover:translate-y-0.5" />
              </button>
              <Link to="/contact" className="btn-primary group">
                Start Project
                <ArrowUpRight className="h-4 w-4 transition-transform duration-500 group-hover:-translate-y-px group-hover:translate-x-px" />
              </Link>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

function ProposalBlock({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div>
      <p className="text-[10.5px] uppercase tracking-[0.22em] text-muted-foreground">{label}</p>
      <p className="mt-2 text-[14.5px] leading-relaxed text-foreground/90">{children}</p>
    </div>
  );
}

// Keep unused imports tree-shakeable
void ArrowRight;
