/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhySynvoraRouteImport } from './routes/why-synvora'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as MyProjectRouteImport } from './routes/my-project'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as HowWeWorkRouteImport } from './routes/how-we-work'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as ApiConsultantRouteImport } from './routes/api/consultant'

const WhySynvoraRoute = WhySynvoraRouteImport.update({
  id: '/why-synvora',
  path: '/why-synvora',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProjectRoute = MyProjectRouteImport.update({
  id: '/my-project',
  path: '/my-project',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const HowWeWorkRoute = HowWeWorkRouteImport.update({
  id: '/how-we-work',
  path: '/how-we-work',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortfolioRoute,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IndustriesRoute,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PortfolioRoute,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => IndustriesRoute,
} as any)
const ApiConsultantRoute = ApiConsultantRouteImport.update({
  id: '/api/consultant',
  path: '/api/consultant',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/my-project': typeof MyProjectRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/solutions': typeof SolutionsRoute
  '/templates': typeof TemplatesRoute
  '/why-synvora': typeof WhySynvoraRoute
  '/api/consultant': typeof ApiConsultantRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/industries/': typeof IndustriesIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/my-project': typeof MyProjectRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/solutions': typeof SolutionsRoute
  '/templates': typeof TemplatesRoute
  '/why-synvora': typeof WhySynvoraRoute
  '/api/consultant': typeof ApiConsultantRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/industries': typeof IndustriesIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/my-project': typeof MyProjectRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/solutions': typeof SolutionsRoute
  '/templates': typeof TemplatesRoute
  '/why-synvora': typeof WhySynvoraRoute
  '/api/consultant': typeof ApiConsultantRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/industries/': typeof IndustriesIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/how-we-work'
    | '/industries'
    | '/my-project'
    | '/portfolio'
    | '/pricing'
    | '/services'
    | '/solutions'
    | '/templates'
    | '/why-synvora'
    | '/api/consultant'
    | '/industries/$slug'
    | '/portfolio/$slug'
    | '/industries/'
    | '/portfolio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/how-we-work'
    | '/my-project'
    | '/pricing'
    | '/services'
    | '/solutions'
    | '/templates'
    | '/why-synvora'
    | '/api/consultant'
    | '/industries/$slug'
    | '/portfolio/$slug'
    | '/industries'
    | '/portfolio'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/how-we-work'
    | '/industries'
    | '/my-project'
    | '/portfolio'
    | '/pricing'
    | '/services'
    | '/solutions'
    | '/templates'
    | '/why-synvora'
    | '/api/consultant'
    | '/industries/$slug'
    | '/portfolio/$slug'
    | '/industries/'
    | '/portfolio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  HowWeWorkRoute: typeof HowWeWorkRoute
  IndustriesRoute: typeof IndustriesRouteWithChildren
  MyProjectRoute: typeof MyProjectRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  PricingRoute: typeof PricingRoute
  ServicesRoute: typeof ServicesRoute
  SolutionsRoute: typeof SolutionsRoute
  TemplatesRoute: typeof TemplatesRoute
  WhySynvoraRoute: typeof WhySynvoraRoute
  ApiConsultantRoute: typeof ApiConsultantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-synvora': {
      id: '/why-synvora'
      path: '/why-synvora'
      fullPath: '/why-synvora'
      preLoaderRoute: typeof WhySynvoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-project': {
      id: '/my-project'
      path: '/my-project'
      fullPath: '/my-project'
      preLoaderRoute: typeof MyProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-work': {
      id: '/how-we-work'
      path: '/how-we-work'
      fullPath: '/how-we-work'
      preLoaderRoute: typeof HowWeWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/industries/': {
      id: '/industries/'
      path: '/'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/api/consultant': {
      id: '/api/consultant'
      path: '/api/consultant'
      fullPath: '/api/consultant'
      preLoaderRoute: typeof ApiConsultantRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface IndustriesRouteChildren {
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
}

const IndustriesRouteChildren: IndustriesRouteChildren = {
  IndustriesSlugRoute: IndustriesSlugRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
}

const IndustriesRouteWithChildren = IndustriesRoute._addFileChildren(
  IndustriesRouteChildren,
)

interface PortfolioRouteChildren {
  PortfolioSlugRoute: typeof PortfolioSlugRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioSlugRoute: PortfolioSlugRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  HowWeWorkRoute: HowWeWorkRoute,
  IndustriesRoute: IndustriesRouteWithChildren,
  MyProjectRoute: MyProjectRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  PricingRoute: PricingRoute,
  ServicesRoute: ServicesRoute,
  SolutionsRoute: SolutionsRoute,
  TemplatesRoute: TemplatesRoute,
  WhySynvoraRoute: WhySynvoraRoute,
  ApiConsultantRoute: ApiConsultantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
